name = "Xranklin"
uuid = "558449b0-171e-4e1f-900f-d076a5ddf486"
authors = ["Thibaut Lienart <tlienart@me.com>"]
version = "0.1.0"

[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
FranklinParser = "796511e7-1510-466f-ad0c-1823c64bcafa"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
CommonMark = "0.8"
FranklinParser = "0.1"
OrderedCollections = "1.3, 1.4"
julia = "1.5"

[extras]
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LiveServer", "Test"]
