name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: tlienart/xranklin-build-action@main
        with:
          SITE_FOLDER: "docs/"
          BASE_URL_PREFIX: "Xranklin.jl"
          PYTHON_LIBS: "matplotlib pandas ansi2html"
          CLEAR_CACHE: ${{ contains(github.event.head_commit.message, '[clear]') }}
          CACHE_KEY: "franklin-cache"
