name: Deploy

on:
  push:
    branches:
      - main
      - ttfx-gaston
  pull_request:
    types: [opened, synchronize]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      ########################################
      - name: SET PREVIEW PATH IF PULL REQUEST
        run: |
          if ${{ github.event_name == 'pull_request' }}
          then
            echo 'preview="previews/PR${{ github.event.number}}"' >> $GITHUB_ENV
          else
            echo 'preview=' >> $GITHUB_ENV
          fi
        shell: bash
      ########################################
      - name: BUILD AND DEPLOY
        uses: tlienart/xranklin-build-action@main
        with:
          SITE_FOLDER: "docs/"
          BASE_URL_PREFIX: "Xranklin.jl"
          PREVIEW: ${{ env.preview }}
          PYTHON_LIBS: "matplotlib pandas ansi2html"
          LUNR: true
      - name: URL INDICATION
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview should be up in a couple of mins at https://tlienart.github.io/Xranklin.jl/${{env.preview}} (if you get a 404, wait 30s then refresh).
        if: github.event_name == 'pull_request'
