name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # try to checkout cache branch if it exists
      # this might fail if it doesn't and that's fine
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages-cache

      # checkout the base branch (main) and ignore if the previous
      # step failed
      - name: Git checkout
        if: always()
        uses: actions/checkout@v2

      # Python
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install numpy # matplotlib

      # Julia
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7
      - run: |
             if [ `git checkout gh-pages-cache -- cache.zip` ]; then
               echo "Using Cache";
               unzip cache.zip;
             else
              echo "No cache found";
             fi
      - run: ls -aoh

      # Website build
      - run: julia -e '
          using Pkg;
          Pkg.add(url="https://github.com/tlienart/Xranklin.jl", rev="main");
          using Xranklin;
          build("docs");'
      - run: 'zip -r cache.zip docs/__cache; mv cache.zip _cache_/cache.zip'
      - run: touch docs/__site/.nojekyll

      # Deployment and caching
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: docs/__site
      - name: Save cache 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages-cache
          FOLDER: _cache_
