name: Preview

on:
  push:
    branches:
      - preview   # note: check rev= in build (Xranklin specific)

env:
  # ADJUST THE FOLLOWING
  # where is the site folder, use "" if the repo root is
  SITE_FOLDER: "docs"
  # if it's a personal site, use "" otherwise use the name of the repo
  BASE_URL_PREFIX: "Xranklin.jl"
  # if it's not a preview, use ""
  PREVIEW: "preview"
  # DON'T CHANGE THE FOLLOWING UNLESS YOU HAVE GOOD REASONS TO
  # >> amounts to build(clear=true)
  CLEAR_CACHE: ${{ contains(github.event.head_commit.message, '[clear]') }}
  # >> change the digit at the end if, for some reason, you believe
  # that the cache used by the github action has an issue
  CACHE_KEY: "franklin-preview-1a"
  # >> if you use PyCall/PyPlot and don't want to use Conda, leave this
  # as is and use the setup-python action along with pip as shown below
  # if you do want to use Conda.jl; change to "" and remove the
  # setup-python step
  PYTHON: "python"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
                ${{ env.SITE_FOLDER }}/__cache
                ${{ env.SITE_FOLDER }}/__site
                ~/.julia/artifacts
                ~/.julia/packages
                !~/.julia/packages/PyPlot
                !~/.julia/packages/PyCall
          key: ${{ runner.os }}-${{ env.CACHE_KEY }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.CACHE_KEY }}-

      # Julia
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      # Python
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install matplotlib

      # Website build
      - run: julia -e '
                using Pkg;
                Pkg.add(
                  url="https://github.com/tlienart/Xranklin.jl",
                  rev="preview"
                  );
                using Xranklin;
                build("${{ env.SITE_FOLDER }}";
                      clear=${{ env.CLEAR_CACHE }},
                      prefix=joinpath(
                        "${{ env.BASE_URL_PREFIX }}",
                        "${{ env.PREVIEW }}"
                        )
                      );'

      # Deployment and caching
      - run: touch ${{ env.SITE_FOLDER }}/__site/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ${{ env.SITE_FOLDER }}/__site
          TARGET-FOLDER: "${{ env.PREVIEW }}"
