name: WGLMakie

on:
  push:
    branches:
      - ttfx

env:
  INDEX: "test/abc_min/index.md"
  SETUP: "using Pkg; Pkg.add([\"WGLMakie\", \"JSServe\"]);"
  BUILD: ""
  PPATH: "Xranklin.jl"
  TARGD: "ttfx/wglmakie"
  SITED: "test/abc_min"
  START: $(date +%s)

jobs:
  wglmakie:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      # =======================================================================
      # -- modify index --
      - name: Set index.md 📖
        run: |
              echo "# TTFX WGLMakie"                                > ${{ env.INDEX }}
              echo "\`\`\`!wgl"                                    >> ${{ env.INDEX }}
              echo "setgvar!(:skiplatex, true)"                    >> ${{ env.INDEX }}
              echo "START2 = time()"                               >> ${{ env.INDEX }}
              echo "using WGLMakie, JSServe"                       >> ${{ env.INDEX }}
              echo "WGLMakie.activate!()"                          >> ${{ env.INDEX }}
              echo "<|(io, o) = show(io, MIME\"text/html\"(), o)"  >> ${{ env.INDEX }}
              echo "io = IOBuffer()"                               >> ${{ env.INDEX }}
              echo "io <| Page(exportable=true, offline=true)"     >> ${{ env.INDEX }}
              echo "io <| scatter(1:4)"                            >> ${{ env.INDEX }}
              echo "io <| surface(rand(4,4))"                      >> ${{ env.INDEX }}
              echo "io <| Slider(1:3)"                             >> ${{ env.INDEX }}
              echo "String(take!(io))"                             >> ${{ env.INDEX }}
              echo "\`\`\`"                                        >> ${{ env.INDEX }}
              echo "\\htmlshow{wgl}"                               >> ${{ env.INDEX }}
              echo "# TIME"                                  >> ${{ env.INDEX }}
              echo "\`\`\`!"                                 >> ${{ env.INDEX }}
              echo "using Dates"                             >> ${{ env.INDEX }}
              echo "t0  = datetime2unix(now())"              >> ${{ env.INDEX }}
              echo "delta  = t0 - ${{ env.START  }}"         >> ${{ env.INDEX }}
              echo "delta2 = t0 - START2"                    >> ${{ env.INDEX }}
              echo "delta  = round(delta  / 60, digits=2)"   >> ${{ env.INDEX }}
              echo "delta2 = round(delta2, digits=2)"        >> ${{ env.INDEX }}
              echo "ps(s) = joinpath(Utils.path(:site), s)"  >> ${{ env.INDEX }}
              echo "write(ps(\"timer\"), delta)"             >> ${{ env.INDEX }}
              echo "write(ps(\"timer2\"), delta2)"           >> ${{ env.INDEX }}
              echo "println(\"Time taken: \$(delta)min.\")"  >> ${{ env.INDEX }}
              echo "println(\"Time taken2: \$(delta2)s.\")"  >> ${{ env.INDEX }}
              echo "\`\`\`"                                  >> ${{ env.INDEX }}
              cat ${{ env.INDEX }}

      # =======================================================================

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.8

      - name: Building website 🚧
        run: ${{ env.BUILD }} julia -e '
                ${{ env.SETUP }};
                Pkg.add(
                  url="https://github.com/tlienart/Xranklin.jl",
                  rev="main"
                  );
                using Xranklin;
                build("${{ env.SITED }}";
                      clear=true,
                      prefix=joinpath(
                        "${{ env.PPATH }}",
                        "${{ env.TARGD }}"
                        )
                      );'

      # Deployment
      - name: No Jekyll
        run: touch ${{ env.SITED }}/__site/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ${{ env.SITED }}/__site
          TARGET-FOLDER: "${{ env.TARGD }}"
